### ISSUE TITLE
text should be first argument to be pipe-able

### ISSUE THREAD

**Issue by jimhester** [MangoTheCat/rematch#2]
Having pattern as the first argument means you need to explicitly set pattern manually.

``` r
txt <- c("one two", "three four")
txt %>% re_match("\\w+")
#> Error: length(pattern) == 1 is not TRUE
txt %>% re_match(pattern = "\\w+")
#>      .match 
#> [1,] "one"  
#> [2,] "three"
```

**Comment by gaborcsardi** [comment]
I know. I thought about that and went with the base R way.

Personally I think that it is best to always write it out, to avoid confusion.

I am not sure about changing it now. Do you think it is very bad?

**Comment by gaborcsardi** [comment]
I suppose we can create a `rematch2` package.

**Comment by jimhester** [comment]
I don't think changing it here would be a problem, there are currently no reverse dependencies of rematch on CRAN.

I do think having the txt argument first is a better API though, also it agrees with one of Hadley's suggestions for pipable APIs

> [The object being transformed should be passed in as the first argument and returned from each object](https://dl.dropboxusercontent.com/u/41902/pipe-dsls.pdf)

**Comment by gaborcsardi** [comment]
On 1 Jul 2016 05:44, "Jim Hester" notifications@github.com wrote:

> I don't think changing it here would be a problem, there are currently no
> reverse dependencies of rematch on CRAN.

I know. But I know that some people use it in non cran projects. And the
change might not lead to error messages, only wrong results. So I prefer
changing the name.

> I do think having the txt argument first is a better API though, also it
> agrees with one of Hadley's suggestions for pipable APIs

I agree with you on both. Lets rename the package. We can just rename the
repo as well I guess.

**Comment by gaborcsardi** [comment]
Done here: https://github.com/MangoTheCat/rematch2/commit/e2b1e8fd24e9da79294e1a3126711adac55f13f9
