### ISSUE TITLE
make .match the last column?

### ISSUE THREAD

**Issue by jennybc** [MangoTheCat/rematch#4]
If you're going to make rematch2, would you consider putting the `.match` column as the last column in the return value of `re_match()`? It is the one I am least interested in and by definition it is the largest, so generally makes the printed result less satisfying.

**Comment by gaborcsardi** [comment]
I don't know, the reason for being the first is that it is always at the same place, should you need it.

It is also easier to drop it, if you don't want it.

Plus it is consistent how other languages do it.

But I agree printing is not the best. Let me see how it looks with tibbles

**Comment by gaborcsardi** [comment]
Moved to https://github.com/MangoTheCat/rematch2/issues/1.
